/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jose.javacomp.Ventanas;

import com.jose.javacomp.Items.Estructuras.Categorias;
import com.jose.javacomp.Items.Estructuras.Opinion;
import com.jose.javacomp.Items.Producto;
import com.jose.javacomp.JavaComp;
import com.jose.javacomp.Utilidades;
import java.time.LocalDate;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author pokes
 */
public class VentanaEditarProducto extends javax.swing.JFrame {

    JFrame lastFrame;
    Integer ident;
    
    private static String imgPath;
    /**
     * Creates new form VentanaEditarProducto
     */
    public VentanaEditarProducto(JFrame lastFrame, Integer ident) {
        initComponents();
        
        this.lastFrame = lastFrame;
        //El tipo (int) no puede establecerse a null al ser primitivo, pero el tipo Integer si
        this.ident = ident;
        
        if (ident == null){
            //Añadimos nuevo producto
            tituloVentanaLabel.setText("Añadir nuevo producto");
            identTF.setText("No generado aún");
        }
        else{
            //Editamos producto ya existente
            Producto p = JavaComp.prod.get(ident);
            
            identTF.setText(String.valueOf(ident));
            tituloTF.setText(p.getTitulo());
            descTA.setText(p.getDesc());
            stockSpinner.setValue(p.getStock());
            precioSpinner.setValue(p.getPrecio());
            categoriaCB.setSelectedIndex(Utilidades.convertirCategoriaIndice(p.getCategoria()));
            ImageIcon img = new ImageIcon(p.getImagen());
            imagenLabel.setIcon(img);
            if (img != null)
                imagenLabel.setText("");
            else
                imagenLabel.setText("Vista previa");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagenFileChooser = new javax.swing.JFileChooser();
        tituloVentanaLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tituloTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        descTA = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        identTF = new javax.swing.JTextField();
        imagenLabel = new javax.swing.JLabel();
        cambiarImagenButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        stockSpinner = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        confirmarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        precioSpinner = new javax.swing.JSpinner();
        jSeparator2 = new javax.swing.JSeparator();
        categoriaCB = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        imagenFileChooser.setDialogTitle("Elige una imagen");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Información del producto (JavaComp)");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tituloVentanaLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloVentanaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloVentanaLabel.setText("Editar información del producto");

        jLabel1.setText("Título:");

        jLabel2.setText("Descripción:");

        descTA.setColumns(20);
        descTA.setRows(5);
        jScrollPane1.setViewportView(descTA);

        jLabel3.setText("Identificación:");
        jLabel3.setEnabled(false);

        identTF.setEnabled(false);

        imagenLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        imagenLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenLabel.setText("Vista previa");
        imagenLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        cambiarImagenButton.setText("Cambiar imagen");
        cambiarImagenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarImagenButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Precio:");

        stockSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000000, 1));

        jLabel6.setText("Stock:");

        confirmarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confirmarButton.setText("Confirmar");
        confirmarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        precioSpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(1000000.0f), Float.valueOf(1.0f)));

        categoriaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Componentes", "Ordenadores", "Móviles y telefonía", "Multimedia", "Consolas y videojuegos" }));

        jLabel7.setText("Categoría:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("JavaComp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel8)
                .addGap(15, 15, 15)
                .addComponent(tituloVentanaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirmarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoriaCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(identTF))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tituloTF, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(precioSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stockSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cambiarImagenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imagenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(tituloVentanaLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(identTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(precioSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stockSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(imagenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cambiarImagenButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmarButton)
                    .addComponent(cancelarButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        this.dispose();
        lastFrame.setVisible(true);
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void cambiarImagenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarImagenButtonActionPerformed
        VentanaSeleccionImagen vsi = new VentanaSeleccionImagen(this);
        vsi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cambiarImagenButtonActionPerformed

    public static void cambiarImagen(String imagen){
        imgPath = imagen;

        System.out.println("Imagen cargada de: " + imagen);
    }
    
    private void confirmarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarButtonActionPerformed
        String titulo = tituloTF.getText();
        String desc = descTA.getText();
        Categorias categoria = Utilidades.convertirIndiceCategoria(categoriaCB.getSelectedIndex());
        float precio;
        try{ precio = (float)precioSpinner.getValue(); }
        catch (Exception e){
            errorRegistro("Precio del producto no válido");
            return;
        }
        int stock ;
        try{ stock = (int)stockSpinner.getValue(); }
        catch (Exception e){
            errorRegistro("Número de stock no válido");
            return;
        }
        
        if (ident == null){
            int newIdent = Utilidades.generarIdentificacion();
            LocalDate fecha = LocalDate.now();
            
            JavaComp.prod.put(newIdent, new Producto(titulo, desc, categoria, precio, imgPath, stock, fecha, new HashMap<Integer, Opinion>()));
        }
        else{
            Producto p = JavaComp.prod.get(ident);
            
            p.setTitulo(titulo);
            p.setDesc(desc);
            p.setCategoria(categoria);
            p.setPrecio(precio);
            p.setImagen(imgPath);
            p.setStock(stock);
        }
        
        this.dispose();
        lastFrame.setVisible(true);
    }//GEN-LAST:event_confirmarButtonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        ImageIcon img = new ImageIcon(imgPath);
        imagenLabel.setIcon(img);
        if (img != null)
            imagenLabel.setText("");
        else
            imagenLabel.setText("Vista previa");
    }//GEN-LAST:event_formComponentShown

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
        lastFrame.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void errorRegistro(String causa){
        JOptionPane.showMessageDialog(this, 
                    causa,
                    "Error en el producto",
                    JOptionPane.ERROR_MESSAGE);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambiarImagenButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JComboBox<String> categoriaCB;
    private javax.swing.JButton confirmarButton;
    private javax.swing.JTextArea descTA;
    private javax.swing.JTextField identTF;
    private javax.swing.JFileChooser imagenFileChooser;
    private javax.swing.JLabel imagenLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner precioSpinner;
    private javax.swing.JSpinner stockSpinner;
    private javax.swing.JTextField tituloTF;
    private javax.swing.JLabel tituloVentanaLabel;
    // End of variables declaration//GEN-END:variables
}
