/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jose.javacomp.Ventanas;

import com.jose.javacomp.Items.Producto;
import com.jose.javacomp.JavaComp;
import com.jose.javacomp.Utilidades;
import java.io.File;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pokes
 */
public class VentanaSeleccionImagen extends javax.swing.JFrame {
    VentanaEditarProducto lastFrame;
    /**
     * Creates new form VentanaSeleccionImagen
     */
    public VentanaSeleccionImagen(VentanaEditarProducto lastFrame) {
        initComponents();
        
        this.lastFrame = lastFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        imgTable = new JTable(){
            public boolean editCellAt(int row, int column, java.util.EventObject e) {
                return false;
            }
        };
        cancelarButton = new javax.swing.JButton();
        confirmarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seleccione una imagen (JavaComp)");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        DefaultTableModel model = new DefaultTableModel(
            new Object [] {
                "Foto", "Archivo"
            }, 0
        ) {
            public Class getColumnClass(int column){
                return getValueAt(0, column).getClass();
            }
        };
        imgTable.setModel(model);
        jScrollPane1.setViewportView(imgTable);
        imgTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        imgTable.setRowHeight(100);
        imgTable.getColumn("Foto").setPreferredWidth(100);
        imgTable.getColumn("Archivo").setPreferredWidth(352);

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        confirmarButton.setText("Confirmar");
        confirmarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirmarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmarButton)
                    .addComponent(cancelarButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarButtonActionPerformed
        int row = imgTable.getSelectedRow();
        if (row < 0){
            JOptionPane.showMessageDialog(this, 
                "Para cambiar la imagen debe seleccionar una de la lista",
                "Error en selección de imagen",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        this.dispose();
        lastFrame.setVisible(true);
        lastFrame.cambiarImagen(String.valueOf(imgTable.getValueAt(row, 1)));
    }//GEN-LAST:event_confirmarButtonActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        this.dispose();
        lastFrame.setVisible(true);
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        File imgFile = new File("Imagenes/");
        if (imgFile.exists()){
            
        DefaultTableModel dtm = (DefaultTableModel)imgTable.getModel();
            for (File f : imgFile.listFiles()){
                try{
                    dtm.addRow(new Object[]{
                    Utilidades.escalarImagen(f.getPath(), 100, 100),
                    f.getPath()
                    });
                }
                catch (Exception e){
                    System.out.println("No se pudo cargar la imagen: " + f.getName());
                }
            }
        }
        else{
            imgFile.mkdirs();
        }
    }//GEN-LAST:event_formComponentShown

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
        lastFrame.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButton;
    private javax.swing.JButton confirmarButton;
    private javax.swing.JTable imgTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
