/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jose.javacomp.Ventanas;

import com.jose.javacomp.Items.ProductoCarrito;
import com.jose.javacomp.Usuarios.Cliente;
import java.io.File;
import java.io.FileOutputStream;
import java.io.PrintWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pokes
 */
public class VentanaCarrito extends javax.swing.JFrame {
    JFrame lastFrame;
    Cliente c;
    
    /**
     * Creates new form VentanaCarrito
     */
    public VentanaCarrito(JFrame lastFrame, Cliente c) {
        initComponents();
        
        this.lastFrame = lastFrame;
        this.c = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        carritoTable = new JTable(){
            public boolean editCellAt(int row, int column, java.util.EventObject e) {
                return false;
            }
        };
        cancelarButton = new javax.swing.JButton();
        procesarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Carrito (JavaComp)");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        DefaultTableModel model = new DefaultTableModel(
            new Object [] {
                "Nombre", "Descripción", "Unidades", "Precio"
            }, 0
        );
        carritoTable.setModel(model);
        jScrollPane1.setViewportView(carritoTable);
        carritoTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        carritoTable.setRowHeight(50);
        carritoTable.getColumn("Nombre").setPreferredWidth(100);
        carritoTable.getColumn("Descripción").setPreferredWidth(250);
        carritoTable.getColumn("Unidades").setPreferredWidth(98);
        carritoTable.getColumn("Precio").setPreferredWidth(98);

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        procesarButton.setText("Procesar pedido");
        procesarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(procesarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton)
                    .addComponent(procesarButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        this.dispose();
        lastFrame.setVisible(true);
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        DefaultTableModel dtm = (DefaultTableModel)carritoTable.getModel();
        dtm.setRowCount(0);
        
        for (ProductoCarrito pc : c.getCarrito()){
            dtm.addRow(new Object[]{
                pc.getTitulo(),
                pc.getDesc(),
                pc.getCantidad(),
                pc.getPrecio()});
        }
    }//GEN-LAST:event_formComponentShown

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
        lastFrame.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void procesarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesarButtonActionPerformed
        LocalDateTime fecha = LocalDateTime.now();
        String factura = fecha.format(DateTimeFormatter.ofPattern("dd-MM-yyyy_HH-mm-ss_SSS")) + ".txt";
        
        try{
            File f = new File("Facturas/");
            if (!f.exists())
                f.mkdirs();
            FileOutputStream fos = new FileOutputStream("Facturas/factura_" + factura);
            PrintWriter s = new PrintWriter(fos);
            
            s.println("-----------------------");
            s.print("Factura del: " + fecha.format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss")));
            s.println("-----------------------");
            
            int i = 1;
            for (ProductoCarrito pc : c.getCarrito()){
                s.println(i++ + ":");
                s.println(" Producto: " + pc.getTitulo());
                s.println(" Descripción: " + pc.getDesc());
                s.println(" Cantidad: " + pc.getCantidad());
                s.println(" Precio: " + pc.getPrecio());
                s.println("");
            }
            
            fos.close();
            s.close();
        }
        catch(Exception e){
            System.out.println("No se pudo guardar la factura");
            e.printStackTrace();
        }
        
        c.getCarrito().clear();
        JOptionPane.showMessageDialog(this, 
                "Productos comprados correctamente. Se ha generado una factura con el nombre " + factura,
                "Operación completada",
                JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
        lastFrame.setVisible(true);
    }//GEN-LAST:event_procesarButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButton;
    private javax.swing.JTable carritoTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton procesarButton;
    // End of variables declaration//GEN-END:variables
}
